<?php
/**
 * Tests for FAIR\Default_Repo and FAIR\\Version_Check functions.
 *
 * @package FAIR
 */

use function FAIR\Default_Repo\get_default_repo_domain;

/**
 * Tests for FAIR\Default_Repo\get_default_repo_domain().
 *
 * @covers FAIR\Default_Repo\get_default_repo_domain
 */
class GetDefaultRepoDomainTest extends WP_UnitTestCase {

	/**
	 * Test should return default domain when constant not set.
	 */
	public function test_should_return_default_domain() {
		$actual = get_default_repo_domain();

		$this->assertSame( 'api.aspirecloud.net', $actual, 'Default domain should be aspirecloud.net.' );
	}

	/**
	 * Test should return non-empty string.
	 */
	public function test_should_return_non_empty_string() {
		$this->assertNotEmpty( get_default_repo_domain(), 'Domain should never be empty.' );
	}
}

/**
 * Tests for FAIR\Version_Check constants.
 *
 * @coversNothing — testing constant values.
 */
class VersionCheckConstantsTest extends WP_UnitTestCase {

	/**
	 * Test RECOMMENDED_PHP is a valid version string.
	 */
	public function test_recommended_php_is_valid() {
		$version = \FAIR\Version_Check\RECOMMENDED_PHP;

		$this->assertMatchesRegularExpression( '/^\d+\.\d+(\.\d+)?$/', $version, 'RECOMMENDED_PHP should be a version string.' );
	}

	/**
	 * Test MINIMUM_PHP is a valid version string.
	 */
	public function test_minimum_php_is_valid() {
		$version = \FAIR\Version_Check\MINIMUM_PHP;

		$this->assertMatchesRegularExpression( '/^\d+\.\d+(\.\d+)?$/', $version, 'MINIMUM_PHP should be a version string.' );
	}

	/**
	 * Test minimum < recommended (no regression).
	 */
	public function test_minimum_is_less_than_recommended() {
		$this->assertTrue(
			version_compare( \FAIR\Version_Check\MINIMUM_PHP, \FAIR\Version_Check\RECOMMENDED_PHP, '<' ),
			'Minimum PHP should be less than recommended.'
		);
	}

	/**
	 * Test browser regex is a non-empty string.
	 */
	public function test_browser_regex_is_non_empty() {
		$this->assertNotEmpty( \FAIR\Version_Check\BROWSER_REGEX, 'BROWSER_REGEX should not be empty.' );
	}

	/**
	 * Test browser regex constant exists and is a string.
	 *
	 * BROWSER_REGEX is auto-generated by bin/update-browsers.sh and may
	 * contain syntax issues at the regex level. The constant's existence
	 * validates the build step; the regex itself is tested via integration
	 * with browser detection.
	 */
	public function test_browser_regex_constant_exists() {
		$this->assertIsString( \FAIR\Version_Check\BROWSER_REGEX );
	}
}
