<?php
/**
 * Tests for Ed25519 signature verification.
 *
 * Verifies the DID → trusted key → signature verification pipeline
 * using real Ed25519 key fixtures generated by tests/fixtures/keys/generate.php.
 *
 * @package FAIR\Tests\Updater
 */

declare( strict_types=1 );

namespace FAIR\Tests\Updater;

use FAIR\DID\Crypto\DidCodec;
use FAIR\Packages;
use PHPUnit\Framework\TestCase;

/**
 * @group signature
 */
class SignatureVerificationTest extends TestCase {

	/**
	 * Path to the key fixture directory relative to project root.
	 */
	private string $fixture_dir;

	/**
	 * DID document fixture (contains public key in multibase).
	 *
	 * @var array<string, mixed>
	 */
	private array $did_doc;

	/**
	 * Release document fixture (contains signature in base64url).
	 *
	 * @var array<string, mixed>
	 */
	private array $release_doc;

	protected function setUp(): void {
		parent::setUp();
		$this->fixture_dir = dirname( __DIR__, 3 ) . '/fixtures/keys/';

		$did_doc_data = file_get_contents( $this->fixture_dir . 'did-doc-signed.json' );
		$this->assertNotFalse( $did_doc_data, 'DID doc fixture missing. Run: composer run test:generate-keys' );
		$this->did_doc = json_decode( $did_doc_data, true );

		$release_data = file_get_contents( $this->fixture_dir . 'release-doc-signed.json' );
		$this->assertNotFalse( $release_data, 'Release doc fixture missing. Run: composer run test:generate-keys' );
		$this->release_doc = json_decode( $release_data, true );
	}

	/**
	 * Test that DidCodec::from_multibase_key correctly decodes the public key.
	 */
	public function test_from_multibase_key_decodes_ed25519(): void {
		$multibase = $this->did_doc['verificationMethod'][0]['publicKeyMultibase'];
		$this->assertStringStartsWith( 'z', $multibase, 'Multibase should have base58btc prefix.' );

		$decoded = DidCodec::from_multibase_key( $multibase );

		$this->assertIsArray( $decoded );
		$this->assertArrayHasKey( 'codec', $decoded );
		$this->assertArrayHasKey( 'key', $decoded );

		// Ed25519 multicodec prefix: 0xed01.
		$this->assertSame( DidCodec::MULTICODEC_ED25519_PUB, $decoded['codec'] );

		// Ed25519 public keys are exactly 32 bytes.
		$this->assertSame( 32, strlen( $decoded['key'] ) );
	}

	/**
	 * Test that the decoded key matches what we generated.
	 * Loads the private keypair fixture (gitignored, generated at test start).
	 */
	public function test_decoded_key_matches_keypair_fixture(): void {
		$keypair_file = $this->fixture_dir . 'ed25519-keypair.json';
		$this->assertFileExists( $keypair_file, 'Keypair fixture should exist. Run: composer run test:generate-keys' );

		$keypair = json_decode( file_get_contents( $keypair_file ), true );

		$multibase = $this->did_doc['verificationMethod'][0]['publicKeyMultibase'];
		$decoded = DidCodec::from_multibase_key( $multibase );

		$this->assertSame(
			$keypair['public_key_hex'],
			bin2hex( $decoded['key'] ),
			'Decoded key should match the keypair public key.'
		);
	}

	/**
	 * Test that get_fair_signing_keys filters DID doc correctly.
	 */
	public function test_get_fair_signing_keys_filters_by_multikey_and_id(): void {
		$keys = Packages\get_fair_signing_keys( $this->did_doc );

		$this->assertIsArray( $keys );
		$this->assertNotEmpty( $keys, 'Should find at least one FAIR signing key.' );
		$this->assertSame( 'Multikey', $keys[0]['type'] );
		$this->assertStringContainsString( 'fair', $keys[0]['id'] );
	}

	/**
	 * Test that non-Multikey entries are filtered out.
	 */
	public function test_get_fair_signing_keys_rejects_non_multikey(): void {
		$doc = $this->did_doc;
		$doc['verificationMethod'][] = [
			'id'         => $doc['id'] . '#other-key',
			'type'       => 'JsonWebKey2020',
			'publicKeyJwk' => [ 'kty' => 'OKP' ],
		];

		$keys = Packages\get_fair_signing_keys( $doc );

		// Should still only return the Multikey entry.
		$this->assertCount( 1, $keys );
	}

	/**
	 * Test that non-fair key IDs are filtered out.
	 */
	public function test_get_fair_signing_keys_rejects_non_fair_fragment(): void {
		$doc = $this->did_doc;
		$doc['verificationMethod'][] = [
			'id'                  => $doc['id'] . '#atproto',
			'type'                => 'Multikey',
			'publicKeyMultibase'  => 'zAtprotoPlaceholder42',
		];

		$keys = Packages\get_fair_signing_keys( $doc );

		// Should still only return the 'fair-*' key.
		$this->assertCount( 1, $keys );
	}

	/**
	 * Test that get_fair_signing_keys returns empty for missing verificationMethod.
	 */
	public function test_get_fair_signing_keys_empty_for_missing_methods(): void {
		$doc = $this->did_doc;
		unset( $doc['verificationMethod'] );

		$keys = Packages\get_fair_signing_keys( $doc );
		$this->assertEmpty( $keys );
	}

	/**
	 * Test that get_fair_signing_keys returns empty for empty verificationMethod.
	 */
	public function test_get_fair_signing_keys_empty_for_empty_methods(): void {
		$doc = $this->did_doc;
		$doc['verificationMethod'] = [];

		$keys = Packages\get_fair_signing_keys( $doc );
		$this->assertEmpty( $keys );
	}

	/**
	 * Test the full signature verification using sodium directly.
	 *
	 * This tests the exact signature format FAIR uses: base64url (no-padding)
	 * Ed25519 detached signature over file content.
	 */
	public function test_signature_verifies_against_public_key(): void {
		$decoded = DidCodec::from_multibase_key(
			$this->did_doc['verificationMethod'][0]['publicKeyMultibase']
		);
		$public_key = $decoded['key'];

		// Get the signature from the release doc.
		$sig_base64url = $this->release_doc['artifacts']['package'][0]['signature'];
		$this->assertNotEmpty( $sig_base64url );

		// Decode signature from base64url (no-padding) — same as production code.
		$signature = sodium_base642bin( $sig_base64url, SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING );
		$this->assertNotFalse( $signature );
		$this->assertSame( 64, strlen( $signature ), 'Ed25519 signature should be 64 bytes.' );

		// Sign the zip content that was signed.
		$zip_path = dirname( $this->fixture_dir ) . '/zips/hello-dolly.zip';
		$this->assertFileExists( $zip_path, 'hello-dolly.zip should exist as a test fixture.' );
		$zip_content = file_get_contents( $zip_path );

		// Verify.
		$verified = sodium_crypto_sign_verify_detached( $signature, $zip_content, $public_key );
		$this->assertTrue( $verified, 'The signature should verify against the zip content.' );
	}

	/**
	 * Test that a tampered zip fails verification.
	 */
	public function test_tampered_zip_fails_verification(): void {
		$decoded = DidCodec::from_multibase_key(
			$this->did_doc['verificationMethod'][0]['publicKeyMultibase']
		);
		$public_key = $decoded['key'];

		$sig_base64url = $this->release_doc['artifacts']['package'][0]['signature'];
		$signature = sodium_base642bin( $sig_base64url, SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING );

		// Tamper with the content.
		$tampered = 'this is not the original zip content';

		$verified = sodium_crypto_sign_verify_detached( $signature, $tampered, $public_key );
		$this->assertFalse( $verified, 'Tampered content should fail verification.' );
	}

	/**
	 * Test that a wrong public key fails verification.
	 */
	public function test_wrong_public_key_fails_verification(): void {
		$sig_base64url = $this->release_doc['artifacts']['package'][0]['signature'];
		$signature = sodium_base642bin( $sig_base64url, SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING );

		$zip_path = dirname( $this->fixture_dir ) . '/zips/hello-dolly.zip';
		$zip_content = file_get_contents( $zip_path );

		// Generate a DIFFERENT keypair.
		$wrong_keypair = sodium_crypto_sign_keypair();
		$wrong_public = sodium_crypto_sign_publickey( $wrong_keypair );

		$verified = sodium_crypto_sign_verify_detached( $signature, $zip_content, $wrong_public );
		$this->assertFalse( $verified, 'A different public key should fail verification.' );
	}

	/**
	 * Test that a wrong signature fails verification.
	 */
	public function test_wrong_signature_fails_verification(): void {
		$decoded = DidCodec::from_multibase_key(
			$this->did_doc['verificationMethod'][0]['publicKeyMultibase']
		);
		$public_key = $decoded['key'];

		$zip_path = dirname( $this->fixture_dir ) . '/zips/hello-dolly.zip';
		$zip_content = file_get_contents( $zip_path );

		// Generate a signature with a different keypair.
		$other_keypair = sodium_crypto_sign_keypair();
		$other_secret = sodium_crypto_sign_secretkey( $other_keypair );
		$wrong_sig = sodium_crypto_sign_detached( $zip_content, $other_secret );

		$verified = sodium_crypto_sign_verify_detached( $wrong_sig, $zip_content, $public_key );
		$this->assertFalse( $verified, 'A signature from a different key should fail verification.' );
	}

	/**
	 * Test that the base64url signature format is correct (no padding).
	 */
	public function test_signature_is_base64url_no_padding(): void {
		$sig = $this->release_doc['artifacts']['package'][0]['signature'];

		// base64url should not contain '+' or '/' or '='.
		$this->assertStringNotContainsString( '+', $sig, 'Should be URL-safe (no +).' );
		$this->assertStringNotContainsString( '/', $sig, 'Should be URL-safe (no /).' );
		$this->assertStringNotContainsString( '=', $sig, 'Should be no-padding (no =).' );
	}

	/**
	 * Test that the decoded signature is exactly 64 bytes (Ed25519).
	 */
	public function test_signature_is_64_bytes_when_decoded(): void {
		$sig = $this->release_doc['artifacts']['package'][0]['signature'];
		$decoded = sodium_base642bin( $sig, SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING );

		$this->assertSame( 64, strlen( $decoded ), 'Decoded signature should be 64 bytes.' );
	}
}
