name: PHP coding standards

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  lint:
    name: Run coding standards checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      WP_ENV_HOME: .cache/wp-env

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false

      - name: Setup cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: ${{ runner.os }}-${{ hashFiles('composer.json', 'package.json') }}
          path: |
            .cache

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Start the development environment
        run: npm run env start

      - name: Install Composer dependencies
        run: npm run test:php:install-deps

      - name: Lint PHPCS
        # TODO: Remove the flag once all warnings are fixed.
        run: npm run lint:php:phpcs -- -- -- --warning-severity=0

      - name: Run PHPStan
        run: npm run lint:php:phpstan

