name: Publish FAIR Metadata

on:
  workflow_run:
    workflows: ["Upload Release Asset"]
    types: [completed]
  workflow_dispatch:
    inputs:
      version:
        description: Version tag (for example v1.2.3)
        required: false
        type: string

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get tag
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ inputs.version }}" ]]; then
            echo "tag=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
          fi

      - name: Publish to FAIR
        uses: fairpm/fair-pulse@v1 # not using sha hash for now, it's our own action anyway
        with:
          version: ${{ steps.tag.outputs.tag }}
          artifact-name: ${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.zip
          upload-metadata: 'true'
        env:
          FAIR_VERIFICATION_KEY_PRIVATE: ${{ secrets.FAIR_VERIFICATION_KEY_PRIVATE }}
          FAIR_VERIFICATION_KEY_PUBLIC: ${{ secrets.FAIR_VERIFICATION_KEY_PUBLIC }}
          FAIR_DID: ${{ vars.FAIR_DID }}
